---
# handlers file for docker-swarm-atomic

- name: restart docker-latest
  become: yes
  service: name=docker-latest state=restarted

- name: restart docker
  become: yes
  service: name=docker state=restarted

- name: restart chrony
  become: yes
  service: name=chronyd state=restarted
